#!/bin/sh

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh

bspc rule -r "*"

#BSPWM configuration
bspc config border_radius              8
bspc config border_width               2
bspc config window_gap                 10
bspc config top_padding                36
bspc config bottom_padding             10
bspc config left_padding               10
bspc config right_padding              10
bspc config single_monocle             false
bspc config split_ratio                0.50
bspc config borderless_monocle         true
bspc config gapless_monocle            true
bspc config focus_follows_pointer      true
bspc config pointer_modifier           mod4
bspc config pointer_action1            move
bspc config pointer_action2            resize_side
bspc config pointer_action3            resize_corner
bspc config remove_disabled_monitors   true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color		"#bd93f9"
bspc config active_border_color		"#bd93f9"
bspc config focused_border_color	"#f1fa8c"
bspc config presel_feedback_color	"#f1fa8c"

#Monitors
bspc monitor LVDS-1 -d 1 2 3 4 5
bspc monitor HDMI-1 -d 6 7 8 9 10

#Floating applications
bspc rule -a Arandr state=floating
bspc rule -a feh state=floating
bspc rule -a Font-manager state=floating
bspc rule -a Nitrogen state=floating
